import 'reflect-metadata';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { test } from 'node:test';
import { Pool } from 'pg';
import { schema as versionOne } from '../src/database/schema';
import { managementSchema } from '../src/database/management.schema';
import { faresSchema } from '../src/database/fares.schema';

const databaseUrl = process.env.TEST_DATABASE_URL ?? process.env.HISTORY_TEST_DATABASE_URL;
test('version 4 preserves renamed profiles, existing enrollment, bills, attendance and weekday defaults', { skip: !databaseUrl }, async t => {
  const schema = `shift_migration_${randomUUID().replaceAll('-', '')}`;
  const setup = new Pool({ connectionString: databaseUrl });
  await setup.query(`CREATE SCHEMA ${schema}`);
  const isolated = new URL(databaseUrl!);
  isolated.searchParams.set('options', `-c search_path=${schema}`);
  const pool = new Pool({ connectionString: isolated.toString() });
  const ids = { guardian: randomUUID(), vehicle: randomUUID(), route: randomUUID(), stop: randomUUID(), request: randomUUID(), service: randomUUID(), bill: randomUUID(), attendance: randomUUID() };
  await pool.query(versionOne);
  await pool.query(managementSchema);
  await pool.query(faresSchema);
  await pool.query('CREATE TABLE app_migrations(version INTEGER PRIMARY KEY); INSERT INTO app_migrations VALUES(1),(2),(3)');
  const timestamp = '2026-09-01T00:00:00.000Z';
  await pool.query(`INSERT INTO users(id,name,phone,"passwordHash",role,"createdAt") VALUES($1,'Guardian','01712345678','legacy-password','GUARDIAN',$2)`, [ids.guardian, timestamp]);
  await pool.query(`INSERT INTO vehicles(id,name,plate,imei,"createdAt","updatedAt") VALUES($1,'Van','MIGRATE-01','868720065798376',$2,$2)`, [ids.vehicle, timestamp]);
  await pool.query(`INSERT INTO routes(id,name,"vehicleId","monthlyAmount") VALUES($1,'Route',$2,200000)`, [ids.route, ids.vehicle]);
  await pool.query(`INSERT INTO stops(id,"routeId",name,position) VALUES($1,$2,'Stop',0)`, [ids.stop, ids.route]);
  await pool.query(`INSERT INTO service_requests(id,"guardianId","studentName","routeId","stopId",status,"createdAt","className",roll) VALUES($1,$2,'Old name',$3,$4,'APPROVED',$5,'Old class','1')`, [ids.request, ids.guardian, ids.route, ids.stop, timestamp]);
  await pool.query(`INSERT INTO subscriptions(id,"guardianId","requestId","studentName","routeId","stopId","monthlyAmount",status,"startedAt") VALUES($1,$2,$3,'Renamed child',$4,$5,200000,'ACTIVE',$6)`, [ids.service, ids.guardian, ids.request, ids.route, ids.stop, timestamp]);
  await pool.query('UPDATE students SET "className"=$1,roll=$2,"pickupAddress"=$3 WHERE id=$4', ['Updated class', '42', 'Existing pickup', ids.service]);
  await pool.query(`INSERT INTO bills(id,"subscriptionId","guardianId",month,amount,status,"createdAt") VALUES($1,$2,$3,'2026-09',200000,'UNPAID',$4)`, [ids.bill, ids.service, ids.guardian, timestamp]);
  await pool.query(`INSERT INTO attendance(id,"studentId",date,status,"updatedAt","recordedBy") VALUES($1,$2,'2026-09-04','PRESENT',$3,$4)`, [ids.attendance, ids.service, timestamp, ids.guardian]);
  const beforeBill = (await pool.query('SELECT * FROM bills WHERE id=$1', [ids.bill])).rows[0];
  const beforeAttendance = (await pool.query('SELECT * FROM attendance WHERE id=$1', [ids.attendance])).rows[0];
  process.env.DATABASE_URL = isolated.toString();
  const { DatabaseService } = require('../dist/database/database.service');
  const db = new DatabaseService();
  t.after(async () => { await db.onApplicationShutdown(); await pool.end(); await setup.query(`DROP SCHEMA ${schema} CASCADE`); await setup.end(); });
  await db.onModuleInit();
  const service = await db.get('SELECT * FROM subscriptions WHERE id=$1', ids.service);
  const profile = await db.get('SELECT * FROM student_profiles WHERE id=$1', service.studentId);
  assert.equal(service.id, ids.service);
  assert.equal(service.shiftId, 'MORNING');
  assert.deepEqual(service.operatingDays, [0, 1, 2, 3, 4, 5, 6]);
  assert.equal(profile.studentName, 'Renamed child');
  assert.equal(profile.className, 'Updated class');
  assert.equal(profile.roll, '42');
  assert.equal((await db.get('SELECT "studentId" FROM service_requests WHERE id=$1', ids.request)).studentId, profile.id);
  assert.equal((await db.get('SELECT "pickupAddress" FROM students WHERE id=$1', ids.service)).pickupAddress, 'Existing pickup');
  assert.deepEqual(await db.get('SELECT * FROM bills WHERE id=$1', ids.bill), beforeBill);
  assert.deepEqual(await db.get('SELECT * FROM attendance WHERE id=$1', ids.attendance), beforeAttendance);
  assert.deepEqual((await db.get('SELECT data FROM business_settings WHERE id=1')).data.operatingDays, [0, 1, 2, 3, 4, 5, 6]);
  await db.onModuleInit();
  assert.equal((await db.get('SELECT count(*)::int count FROM student_profiles')).count, 1);
});
