#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

usage() {
  cat <<'HELP'
Usage: bash scripts/local.sh [update|stop|status|logs|config]

  update  Create .env.local on first use and start/update PostgreSQL only
  stop    Stop PostgreSQL while keeping its local volume
  status  Show container status
  logs    Follow PostgreSQL logs
  config  Validate the resolved Compose configuration

The default action is update. All commands use compose.local.yml and .env.local.
They never load the VPS .env or use its Compose project/volume.
HELP
}

action=${1:-update}
if [[ "$action" == --help || "$action" == -h || "${2:-}" == --help || "${2:-}" == -h ]]; then usage; exit 0; fi
[[ $# -le 1 ]] || { usage >&2; exit 2; }
case "$action" in update|stop|status|logs|config) ;; *) usage >&2; exit 2 ;; esac

command -v docker >/dev/null || { echo 'Docker with Compose is required.' >&2; exit 1; }
[[ ! -L .env.local ]] || { echo '.env.local must be a regular file, not a symlink.' >&2; exit 1; }
# A remote Docker context would send local credentials and data to another host.
# Check both overrides and the selected context before any Compose operation.
case "${DOCKER_HOST:-}" in
  ''|unix://*|npipe://*|fd://*) ;;
  *) echo 'Local update requires a local Docker socket; DOCKER_HOST is remote.' >&2; exit 1 ;;
esac
docker_context=$(docker context show)
docker_endpoint=$(docker context inspect "$docker_context" --format '{{.Endpoints.docker.Host}}')
case "$docker_endpoint" in
  unix://*|npipe://*|fd://*) ;;
  *) echo 'Local update requires a local Docker socket; the selected Docker context is remote.' >&2; exit 1 ;;
esac
if [[ "$action" == update && ! -e .env.local ]]; then
  docker info >/dev/null 2>&1 || { echo 'Docker is not running or this user cannot access its daemon.' >&2; exit 1; }
  if docker volume inspect gps-tracker-dev_postgres-data >/dev/null 2>&1; then
    echo 'The local PostgreSQL volume exists but .env.local is missing.' >&2
    echo 'Restore the original .env.local before updating; new passwords would not unlock existing data.' >&2
    exit 1
  fi
  command -v openssl >/dev/null || { echo 'OpenSSL is required to generate local credentials.' >&2; exit 1; }
  umask 077
  postgres_password=$(openssl rand -hex 24)
  app_password=$(openssl rand -hex 24)
  admin_password=$(openssl rand -hex 24)
  # noclobber prevents replacing a file created by another invocation.
  if ( set -C; cat > .env.local <<EOF
# Private, local-only credentials. Generated by scripts/local.sh; never commit.
POSTGRES_PASSWORD=$postgres_password
APP_DB_PASSWORD=$app_password
ADMIN_PHONE=01700000000
ADMIN_PASSWORD=$admin_password
# Local API accepts any non-empty password when this file is loaded.
LOCAL_ALLOW_SHORT_PASSWORDS=true

# Host API bind/ports. Keep 3000/3001 paired for the Android app.
LOCAL_BIND_HOST=127.0.0.1
LOCAL_REST_PORT=3000
LOCAL_SOCKET_PORT=3001
LOCAL_TCP_PORT=5023
LOCAL_POSTGRES_PORT=55432
EOF
  ); then
    echo 'Created private .env.local with random passwords.'
    echo 'Admin login: phone 01700000000; read ADMIN_PASSWORD from .env.local.'
  else
    echo 'Another process created .env.local; using the existing file.'
  fi
fi

[[ -f .env.local ]] || { echo 'Missing .env.local. Run the update command first.' >&2; exit 1; }
if [[ "$(uname -s)" == Darwin ]]; then
  file_mode=$(stat -f %Lp .env.local)
else
  file_mode=$(stat -c %a .env.local)
fi
if (( (8#$file_mode & 077) != 0 )); then
  echo '.env.local is readable by another user. Run chmod 600 .env.local.' >&2
  exit 1
fi
# Compose gives exported shell variables precedence over --env-file. Keep this
# project's credentials and port settings authoritative even in a VPS shell.
unset APP_DB_PASSWORD POSTGRES_PASSWORD ADMIN_PHONE ADMIN_PASSWORD LOCAL_ALLOW_SHORT_PASSWORDS
unset LOCAL_BIND_HOST LOCAL_REST_PORT LOCAL_SOCKET_PORT LOCAL_TCP_PORT LOCAL_POSTGRES_PORT
compose=(docker compose --ansi never --project-name gps-tracker-dev --env-file .env.local -f compose.local.yml)
"${compose[@]}" config --quiet

case "$action" in
  update)
    # Remove the API container from older versions of this local Compose stack.
    # Compose only removes that orphan container; the PostgreSQL volume is kept.
    "${compose[@]}" up -d --remove-orphans --wait --wait-timeout 180 postgres
    "${compose[@]}" ps
    echo 'PostgreSQL is healthy. Start the API on this machine with: npm run start:dev'
    ;;
  stop) "${compose[@]}" down ;;
  status) "${compose[@]}" ps ;;
  logs) "${compose[@]}" logs -f --tail=100 postgres ;;
  config) echo 'Local Compose configuration is valid.' ;;
esac
